### ISSUE TITLE
Typos and details

### ISSUE THREAD

**Issue by elicoidal** [browseinfo/l10n_hk#2]
- Name of the module: Hongkong Localization Chart Account => "Hong Kong - Accounting"
- Logo with the flag of the country
- default Currency is HKD
- in wizard: Hongkong Chart of Accounts => Hong Kong Chart of Accounts
- In my opinion no need for taxes in HK: not sure why they were added.
- Parent for cash and bank account is incorrect (should be Current asset 1111)
- Parent for shared capital is incorrect (there should be 131 Capital)
- Accounts 111410 and 111411 seems to be customer prepayments and should be under "1213 Other liabilities" (with parent = 121 current liability). To be confirmed by Yoshi at it seems duplicated with 121310
- Accounts 111410 and 111411 => Receivable accounts (To be confirmed by Yoshi)
- Accounts 111420 and 111421 => Payable accounts

**Comment by bhavik-browseinfo** [comment]
Thanks Eric!We will work on the changes.And soon ,will upload latest code.

**Comment by bhavik-browseinfo** [comment]
Hello Eric!We have considered all of these changes.Latest branch is also uploaded.If there is something missing ,we welcome your valuable suggestions. 
One again thank you.

**Comment by elicoidal** [comment]
I tried to check out the main branch but seems not the right branch/commit
Eric CAUDAL --
*Eric Caudal* /[Founder and CEO]/
Skype: elico.corp. Phone: + 86 186 2136 1670 (Cell), + 86 21 6211 
8017/27/37 (Office)
*Elico Shanghai* (Shenzhen/Singapore) <http://www.elico-corp.com> /*Odoo 
Gold Partner, best Odoo Partner 2014 for APAC*/
